name: projetflutter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  animated_bottom_navigation_bar: ^1.3.3
  flutter:
    sdk: flutter
    
  http: ^1.2.1
  image_picker: ^1.1.2
  page_transition: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
      - images/
